title: Stephen Dunn 
description: Technical professional experienced in supporting enterprise environments across security, systems, and operational technology. Recognized for taking ownership of complex technical issues, collaborating and driving remediation efforts, and helping maintain secure and reliable infrastructure.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
